config/routes.rb
Creta::Application.routes.draw do
  devise_for :users
  get "articles/index"
  get "articles/create"
  get "articles/new"
  get "articles/edit"
  get "articles/show"
  get "articles/update"
  get "articles/destroy"
  resources :articles

  get "galleries/index"
  get "galleries/show"
  resources :galleries

  root to: "pages#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	belongs_to :gallery
	validates_presence_of :title, :user, :gallery
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	has_many :articles
	validates_presence_of :id, :name
	validates_uniqueness_of :id, :name
end

app/models/gallery_id.rb
class GalleryID
	def initialize(action)
		@action = action
	end

	protected
		def get_id
			case (@action)
				when "cogitatus"							then return 1		# Thoughts
				when "politicus"							then return 2		# Politics
				when "parcus"									then return 3		# Economics
				when "ipsum"									then return 4		# Computers
				when "scientia_physica"				then return 5		# Physical sciences
				when "scientia_naturalis"			then return 6		# Natural sciences
				when "proelium"								then return 7		# Conflicts
				when "humanitas"							then return 8		# Humanities (Culture)
			end
		end

		def set_id
			# Nothing to do for now
			# Setting ID in Gallery Model itself
		end
end

app/models/galleryid.rb
class GalleryID
	def initialize(action)
		@action = action
	end

	protected
		def get_id
			case (@action)
				when "cogitatus"							then return 1		# Thoughts
				when "politicus"							then return 2		# Politics
				when "parcus"									then return 3		# Economics
				when "ipsum"									then return 4		# Computers
				when "scientia_physica"				then return 5		# Physical sciences
				when "scientia_naturalis"			then return 6		# Natural sciences
				when "proelium"								then return 7		# Conflicts
				when "humanitas"							then return 8		# Humanities (Culture)
			end
		end

		def set_id
			# Nothing to do for now
			# Setting ID in Gallery Model itself
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  validates_presence_of :name, :email, :password
end

app/models/user_observer.rb
class UserObserver < ActiveRecord::Base
	# We check if it's a new user
  def before_save(user)
    @is_new_record = user.new_record?
    true
   end

  def after_save(user)
  # If it's not a new user we don't want to send them another welcome email
    if @is_new_record then
      UserMailer.welcome_mail(user.email)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
		def configure_permitted_parameters
		 devise_parameter_sanitizer.for(:sign_up) << :name
		 devise_parameter_sanitizer.for(:account_update) << :name
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index # Show list of articles
    @articles = Article.all
  end

  def create # Action called by New method
    @article = current_user.articles.build(article_params)
    @article.save
    if @article.save
      redirect_to @article, notice: "#{@article.title} was published!" # Redirect to new article's Show page
    else
      render action: 'new'
    end
  end

  def new # Make new article
    @article = current_user.articles.build
  end

  def edit # Edit article
    find_article
  end

  def show # Show individual articles
    find_article
  end

  def update # Action called by Edit method
    find_article
    if @article.update(article_params)
      redirect_to @article, notice: "#{@article.title} was updated!"
    else 
      render action: 'edit'
    end
  end

  def destroy # Action called to delete article entry
    find_article
    @article.destroy
    flash.alert = "#{@article.title} was deleted!"
    redirect_to articles_path
  end

    protected
      def find_article
        @article = Article.find(params[:id])
      end
      def determine_gallery
        @gallery = @article.gallery
      end
      def article_params
        params.require(:article).permit(:title, :subtitle, :body, :gallery_id)
      end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

	def index
		@galleries = Gallery.all
	end

  def create
  end

  def new
  end

  def edit
  end

  def show # Show individual galleries
    find_gallery
    find_articles
  end

  def update
  end

  def destroy
  end

	protected
		def find_by_name(action)
			Gallery.find_by(name: params[action])
		end

		def find_gallery
			@gallery = Gallery.find(params[:id])
		end

		def find_articles
      @articles = @gallery.articles
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-warning error">
      <ul>
        #{messages}
      </ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
	<%= f.input :title %>
	<br>
	<%= f.input :subtitle %>
	<br>
	<%= f.input :body %>
  <br>
  <%= f.association :gallery, collection: Gallery.all(order: 'name'), value_method: :id, prompt: "Choose a Gallery", include_blank: false %>
	<br>
	<%= f.button :submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit An Article</h1>
<br>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<% @articles.each do |article| %>
	<%= link_to article.title, article_path(article) %>
<% end %>
<br>
<% if user_signed_in? %>
	<%= link_to "New Article", new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>Write An Article</h1>
<br>
<%= render 'form' %>

app/views/articles/show.html.erb
<%= @article.title %>
<br>
<%= @article.subtitle %>
<br>
<%= @article.body %>
<br>
Gallery: <%= @article.gallery.name %>
<br>
<% if @article.user == current_user %>
<%= link_to "Edit Article", edit_article_path(@article) %> 
<%= link_to "Delete Article", article_path(@article), method: :delete, confirm: "Are you sure you want to delete this article? #{@article.title} is a good title!" %>
<br>
<% end %>
<%= link_to "All Articles", articles_path %>

app/views/galleries/index.html.erb
<h1>Galleries</h1>
<% @galleries.each do |gallery| %>
	<%= link_to gallery.name, gallery_path(gallery) %>
<% end %>

app/views/galleries/show.html.erb
<%= @gallery.name %>
<br>
<% @articles.each do |article| %>
	<p><%= link_to article.title, article_path(article) %></p>
<% end %>
<br>
<%= link_to "All Galleries", galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Creta" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/index.html.erb
<% unless user_signed_in? %>
	<h1 class="text-center OpenSans">Write.</h1>
<% else %>
	<h1 class="text-center OpenSans">Write something already.</h1>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapser">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Creta", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="collapser">
      <ul class="nav navbar-nav navbar-left">
        <% if user_signed_in? %>
          <li><%= link_to "Articles", articles_path %></li>
        <% end %>
          <li><%= link_to "Galleries", galleries_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "sign-up" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "sign-in" %></li>
        <% else %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-out" %></li>
        <% end %>
          <li><%= link_to "GitHub", "https://github.com/Sachaniman/Creta" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
</div>